apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docusaurus-site
  description: Docusaurus documentation site
  annotations:
    github.com/project-slug: cheating-at-solitaire/docusaurus-site
  links:
    - url: http://docusaurus.local
      title: Docusaurus Documentation
      icon: docs
spec:
  type: website
  lifecycle: production
  owner: guests
  system: examples
