apiVersion: apps/v1
kind: Deployment
metadata:
  name: docusaurus
  labels:
    app: docusaurus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docusaurus
  template:
    metadata:
      labels:
        app: docusaurus
    spec:
      containers:
        - name: docusaurus
          image: docusaurus-site:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
